### ISSUE TITLE
[Release] v0.0.2

### ISSUE THREAD

**Issue by comaniac** [awslabs/slapo#47]
We plan to release v0.0.2 along with the arXiv paper. Here are the action items toward to this release.

- [x] Rename `model_dialect` to `framework_dialect` (#51).
- [x] Move `examples` to `slapo.model_schedule` (#53).
    - [x] Make a unified API for users to apply builtin schedules to HF models (#53).
    (e.g., `model = ApplySchedule("bert-base-uncased", model)`).
- [x] Tutorial with one model (HF BERT or GPT) (#63).

The release date is tentatively 2/14. Accordingly, the following items are deprioritized to v0.0.3:
- Unit tests (#11)
- Support official DeepSpeed 0.8.0 in dialect.

Details can be discussed in this tracking issue.

**Comment by comaniac** [comment]
All tasks are done. I'll prepare the release and upload to PYPI on Monday.
